### DISCUSSION TITLE
Chown/chmod have no effect on Blob mounted on AKS Pods

### DISCUSSION THREAD

**Discussion by NattyPradeep** [kubernetes-sigs/blob-csi-driver#682] [Q&A]
Hello,

We mounted the blob storage as volume mount and we can't change the permissions from "root" to other accounts. What can be done to resolve the issue?. From AKS Pod we are not able to access the volume mount path.

**Comment by andyzhangx** [comment]
`mountPermissions` is only for NFS volume. what's your volume type, by default it's blobfuse.

mountPermissions | mounted folder permissions. The default is 0777, if set as 0, driver will not perform chmod after mount | 0777 | No
-- | -- | -- | --

**Reply by NattyPradeep** [reply]
Looks like it's blobfuse. is there anyways to make it as NFS?. We are mounting blob storage on Pod                                                                                       

blobfuse                                                                                           126G   61M  120G   1% /mnt/EMFT

**Reply by andyzhangx** [reply]
you need to specify `protocl: nfs` in the storage class: https://github.com/kubernetes-sigs/blob-csi-driver/tree/master/deploy/example/nfs
for blobfuse, does `allow_other` mount option works?

https://github.com/kubernetes-sigs/blob-csi-driver/blob/02ba84f85e6ac1ff153a7648297a91425e1db7ed/deploy/example/storageclass-blobfuse.yaml#L12-L13

**Reply by NattyPradeep** [reply]
I tried as - -o allow_other  and NFS still not able to change permissions!. Can you please advise my charts are correct?

mountOptions:
  - -**o allow_other**
parameters:
  protocol: **nfs**


apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: atarifeedlistener-sc-blob
provisioner: blob.csi.azure.com
allowVolumeExpansion: true
mountOptions:
  - -o allow_other
parameters:
  protocol: nfs
  skuName: Standard_LRS
  location: East US
  storageAccount: cordeausecmsa
  resourceGroup: cor-d-eaus-ecm-dctm-rg
  containerName: emft-jobs
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atarifeedlistener-pvc-blob
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: atarifeedlistener-sc-blob

**Reply by andyzhangx** [reply]
here is the nfs protocol storage class example:
https://github.com/kubernetes-sigs/blob-csi-driver/blob/02ba84f85e6ac1ff153a7648297a91425e1db7ed/deploy/example/storageclass-blob-nfs.yaml

**Reply by NattyPradeep** [reply]
so on nfs, we should be able to change the permission on these mounts?

**Reply by andyzhangx** [reply]
yes, of course

**Reply by NattyPradeep** [reply]
If you can confirm these are the changes. will deploy and try out these changes.
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: atarifeedlistener-sc-blob
provisioner: blob.csi.azure.com
allowVolumeExpansion: true
mountOptions:
  - nconnect=8
parameters:
  protocol: nfs
  skuName: Standard_LRS
  location: East US
  storageAccount: cordeausecmsa
  resourceGroup: cor-d-eaus-ecm-dctm-rg
  containerName: emft-jobs
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atarifeedlistener-pvc-blob
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: atarifeedlistener-sc-blob  
```
