### DISCUSSION TITLE
AzureStorageAuthType SPN with Inline volume

### DISCUSSION THREAD

**Discussion by PLCyr** [kubernetes-sigs/blob-csi-driver#839] [Q&A] [answered]
Hi ! I'm trying to use the AzureStorageAuthType SPN with an inline volume (without persistentVolume).
There seems to be an issue for the secret which will contain the clientSecret for the SPN.
I'm not sure if it suppose to work, please advice !

**Comment by andyzhangx** [comment, marked as answer]
try config like following:
```
kubectl create secret generic azure-secret --from-literal azurestoragespnclientsecret="xxx" --type=Opaque
```

```
  volumes:
    - name: persistent-storage
      csi:
        driver: blob.csi.azure.com
        volumeAttributes:
          resourceGroup: EXISTING_RESOURCE_GROUP_NAME
          storageAccount: EXISTING_STORAGE_ACCOUNT_NAME
          containerName: EXISTING_CONTAINER_NAME
          secretName: azure-secret
          AzureStorageAuthType: spn
          AzureStorageSPNClientID:
          AzureStorageSPNTenantID:
          AzureStorageAADEndpoint:
          mountOptions: "-o allow_other --file-cache-timeout-in-seconds=120"  # optional
```
