### ISSUE TITLE
Blobfuse proxy not started after installation

### ISSUE THREAD

**Issue by mweibel** [kubernetes-sigs/blob-csi-driver#1718]
**What happened**:
Setup blob-csi-driver but with `installBlobfuse=false` and `installBlobfuse2=false` and then tried a first mount. However it couldn't mount (context deadline exceeded) and when checking on the node I saw that blobfuse proxy service was not started:
```
# systemctl status blobfuse-proxy.service
● blobfuse-proxy.service - Blobfuse proxy service
     Loaded: loaded (/usr/lib/systemd/system/blobfuse-proxy.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
```

enabling & starting the service then made it work.

**What you expected to happen**:
blobfuse-proxy service is auto started

**How to reproduce it**:
Install blob-csi-driver with the following helm command:
```
helm upgrade \
  --install \
  blob-csi-driver \
  --repo https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts \
  blob-csi-driver \
  --namespace kube-system \
  --set controller.replicas=1 \
  --set node.blobfuseProxy.installBlobfuse=false \
  --set node.blobfuseProxy.installBlobfuse2=false
```

**Anything else we need to know?**:
https://github.com/kubernetes-sigs/blob-csi-driver/blob/e280c04f9020dfe1720ff4360eba1c95f0b57aa8/pkg/blobfuse-proxy/install-proxy.sh#L118-L123

I wonder if we should instead of using those variables, check if the proxy is started and do the systemctl commands in case it's not started?

**Environment**:

- CSI Driver version: v1.25.0
- Kubernetes version (use `kubectl version`): v1.26.0 (local cluster)
- OS (e.g. from /etc/os-release): linux
- Kernel (e.g. `uname -a`): debian 11

The test installation I use is on a local kind cluster and I execute the following additionally to make sure blobfuse installation works:
```
docker exec core-worker bash -c "cd /tmp && \
curl -o packages-microsoft-prod.deb https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb && \
dpkg -i packages-microsoft-prod.deb && \
apt-get update && \
apt-get install -y blobfuse2 fuse3
```

```
kubectl patch daemonset -n kube-system csi-blob-node --patch-file "${SCRIPT_DIR}/csi-blob-node-patch.yaml"
```

where csi-blob-node-patch is:
```
# currently can't be set in helm chart directly and doesn't work in kind clusters beacuse udev is disabled
# can be removed once https://github.com/kubernetes-sigs/blob-csi-driver/pull/1717 is merged and released
spec:
  template:
    spec:
      initContainers:
        - name: install-blobfuse-proxy
          env:
            - name: SET_READ_AHEAD_SIZE
              value: "false"
```

StorageClass I use:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blob-fuse
mountOptions:
- -o allow_other
- --file-cache-timeout-in-seconds=120
- --use-attr-cache=true
- --cancel-list-on-mount-seconds=10
- -o attr_timeout=120
- -o entry_timeout=120
- -o negative_timeout=120
- --log-level=LOG_DEBUG
- --cache-size-mb=1000
parameters:
  protocol: fuse2
  skuName: Premium_LRS
provisioner: blob.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
```
