### ISSUE TITLE
Getting Error : pc error: code = Internal desc = Mount failed with error: rpc error: code = Unknown desc = exit status 1 Error: directory is already mounted

### ISSUE THREAD

**Issue by UthayakumarRakav** [kubernetes-sigs/blob-csi-driver#1817]
### Steps which i followed for this ;
`helm repo add blob-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts`
`helm repo update`

`helm install blob-csi-driver blob-csi-driver/blob-csi-driver --namespace kube-system --set azureSubscriptionID=<subscription-id> --set azureResourceGroup=<resource-group>`

`kubectl create secret generic azure-blob-secret --from-literal=azurestorageaccountname=<storage-account-name> --from-literal=azurestorageaccountkey=<storage-account-key> --namespace default`

**azure-blob-sc.yaml**
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-blob
provisioner: blob.csi.azure.com
parameters:
  containerName: <containername>
  csi.storage.k8s.io/provisioner-secret-name: azure-blob-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: azure-blob-secret
  csi.storage.k8s.io/node-stage-secret-namespace: default
  protocol: fuse
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**azure-blob-pvc.yaml**
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-blob-pvc
spec:
  storageClassName: azure-blob
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
```

 **Deploy a Pod Using the PVC azure-blob-pod.yaml**
```
apiVersion: v1
kind: Pod
metadata:
  name: azure-blob-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /mnt/azure
          name: azure-blob-storage
  volumes:
    - name: azure-blob-storage
      persistentVolumeClaim:
        claimName: azure-blob-pvc
```

After deploying all these when I check the status of deployed pod, its in container creating state.When I see its events getting eeror like 
 **MountVolume.MountDevice failed for volume "pvc-28b31fa0-f2fb-442f-aec0-5489dc6ce210" : rpc error: code = Internal desc = Mount failed with error: rpc error: code = Unknown desc = exit status 1 Error: directory is already mounted , output: Please refer to http://aka.ms/blobmounterror for possible causes and solutions for mount errors.**

Steps that i tried to resolve this:
 
Ran the following command on your Ubuntu VM to check if the directory is already mounted:
`mount | grep blob`

There's an existing mount point related to the Azure Blob CSI Driver, try unmounting it.
`sudo umount /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/blob.csi.azure.com/7282945e6f64e8560530c2d08fbca6e0d708bc11240931c116edb9bd619d5799/globalmount`

So I restarted the affected pods.
```
kubectl delete pod azure-blob-pod
kubectl apply -f azure-blob-pod.yaml
```

Then, check its status.
`kubectl get pods`

But unfortunately got the same error.
 **MountVolume.MountDevice failed for volume "pvc-28b31fa0-f2fb-442f-aec0-5489dc6ce210" : rpc error: code = Internal desc = Mount failed with error: rpc error: code = Unknown desc = exit status 1 Error: directory is already mounted , output: Please refer to http://aka.ms/blobmounterror for possible causes and solutions for mount errors.**

![Image](https://github.com/user-attachments/assets/c10eb70f-017a-4e9c-bc16-2c5fa04f229b)

![Image](https://github.com/user-attachments/assets/a87c8ddd-3a84-4f13-b432-6243c6c64b35)

Here's the PV & PVC details;

**PV**

![Image](https://github.com/user-attachments/assets/fa9c2830-e9f8-495a-a528-670099d104f1)

**PVC**

![Image](https://github.com/user-attachments/assets/a2fcaa33-2934-47cb-a710-6fe4d2cc63b9)

**Please give me a solution for this** **Thanks in Advance.**
