### ISSUE TITLE
Statically provisioned PersistentVolume with persistentVolumeReclaimPolicy: Delete does not delete

### ISSUE THREAD

**Issue by rhaps0dy** [kubernetes-sigs/blob-csi-driver#1826]
**What happened**:

Just like #1616 , the underlying Azure Blob container did not get deleted when deleting a PV with `persistentVolumeReclaimPolicy: Delete`. 

Here is my PV and PVC:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: az-pv-example
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  csi:
    driver: blob.csi.azure.com
    nodeStageSecretRef:
      name: csi-myaccountname
      namespace: storage
    volumeAttributes:
      containerName: adria-catastrophic-goodhart
      isHnsEnabled: "true"
    volumeHandle: az-pv-example
  persistentVolumeReclaimPolicy: Delete
  storageClassName: az-myaccountname
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: az-pvc-example
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: az-myaccountname
  volumeMode: Filesystem
  volumeName: az-pv-example
```

**What you expected to happen**:

The container `adria-catastrophic-goodhart` in account `myaccountname` in Azure Blob should be deleted, but it is not.

**How to reproduce it**:

Create the YAMLs above, editing to set your account name and a container that exists.

Verify that it exists by creating a pod and mounting it (optional but recommended). E.g. something like this:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: minimal-pod
spec:
  containers:
  - name: dummy
    image: busybox
    command:
      - sleep
      - "600" # 600s
    volumeMounts:
    - name: az-pvc-example
      mountPath: /data
  volumes:
  - name: az-pvc-example
    persistentVolumeClaim:
      claimName: az-pvc-example
  restartPolicy: Never
```

Delete the pod. Then run `kubectl delete pvc az-pvc-example`. 

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: v1.25.1
- Kubernetes version (use `kubectl version`):
> Client Version: v1.29.5
> Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
> Server Version: v1.29.10
- OS (e.g. from /etc/os-release): Ubuntu 22.04.4 LTS
- Kernel (e.g. `uname -a`):
```
Linux node02 5.15.0-131-generic #141-Ubuntu SMP Fri Jan 10 21:18:28 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:
