### ISSUE TITLE
Cannot successfully specify server or storageEndpointSuffix for storage class

### ISSUE THREAD

**Issue by Treedy2020** [kubernetes-sigs/blob-csi-driver#1926]
master branch: 1.26.4 & 1.25.4
Before proceeding, I first created the `azure-secret` by
```
kubectl create secret generic azure-secret --from-literal azurestorageaccountname=NAME --from-literal azurestorageaccountkey="KEY" --type=Opaque
```
**storage-class.yaml**
```yaml 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blob-fuse
provisioner: blob.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  containerName: "rainbow"
  server: "xxxx.blob.core.chinacloudapi.cn"
  storageEndpointSuffix: "core.chinacloudapi.cn"
  csi.storage.k8s.io/provisioner-secret-name: azure-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: azure-secret
  csi.storage.k8s.io/node-stage-secret-namespace: default
mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=120
  - --use-attr-cache=true
  - --cancel-list-on-mount-seconds=10
```
**pvc.yaml**
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-blob-pvc
spec:
  accessModes:
    - ReadWriteMany  
  resources:
    requests:
      storage: 10Gi  
  storageClassName: blob-fuse
```
and the describe log for `kubectl describe pvc my-blob-pvc` are following
```
Name:          my-blob-pvc
Namespace:     default
StorageClass:  blob-fuse
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: blob.csi.azure.com
               volume.kubernetes.io/storage-provisioner: blob.csi.azure.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       blob-pod
Events:
  Type     Reason                Age                  From
                                           Message
  ----     ------                ----                 ----
                                           -------
  Normal   ExternalProvisioning  113s (x62 over 17m)  persistentvolume-controller
                                           Waiting for a volume to be created either by the exte
rnal provisioner 'blob.csi.azure.com' or manually by the system administrator. If volume creatio
n is delayed, please verify that the provisioner is running and correctly registered.
  Normal   Provisioning          81s (x7 over 17m)    blob.csi.azure.com_xxx.xxx.xxx
.com_cbdc8cc1-467b-45cb-8318-375d9dad1380  External provisioner is provisioning volume for claim
 "default/my-blob-pvc"
  Warning  ProvisioningFailed    81s (x6 over 14m)    blob.csi.azure.com_xxx.xxx.xxx
.com_cbdc8cc1-467b-45cb-8318-375d9dad1380  failed to provision volume with StorageClass "blob-fu
se": rpc error: code = Internal desc = failed to create container(rainbow) on account() type() r
g() location() size(10), error: Put "https://xxxx.blob.core.windows.net/rainbow?r
estype=container": dial tcp: lookup xxxx.**blob.core.windows.net** on 10.168.6.10:53:
 no such host
```
The issue is that, regardless of whether I set the server or **storageEndpointSuffix** parameters, the PVC always connects to blob.core.windows.net and get an Error.
