### ISSUE TITLE
install-blobfuse-proxy container script failing

### ISSUE THREAD

**Issue by Kevinn1109** [kubernetes-sigs/blob-csi-driver#1940]
**What happened**:
I've downloaded and ran the install-driver.sh file without making any changes, this grabs all yaml files from the Github repository and correctly installs them in my local Minikube cluster. However, the blob-node container doesn't start correctly due to an issue with the install-blobfuse-proxy container. Below is the output of this container:

```
+ nsenter --mount=/proc/1/ns/mnt lsb_release -rs
nsenter: failed to execute lsb_release: No such file or directory
```

Both the PersistentVolume and the PersistentVolumeClaim are mounted correctly, but the container referencing the pvc fails with `MountVolume.MountDevice failed for volume "azure-blob-pv" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name blob.csi.azure.com not found in the list of registered CSI drivers`.

**How to reproduce it**:
Run `minikube start --driver=docker -n 2`, then execute the install-driver.sh script. After a minute`kubectl -n kube-system logs csi-blob-node-xxxxx -c install-blobfuse-proxy` shows the error described above.

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-blob-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: azure-blob-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-blob-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: blob.csi.azure.com
    volumeHandle: devstoreaccount1#assets
    volumeAttributes:
      containerName: assets
      protocol: http
      storageAccount: devstoreaccount1
      azureBlobEndpoint: http://azurite:10000/devstoreaccount1
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
```
Applying the pv and pvc above, followed by a container referencing the azure-blob-pvc claim as a volume will fail with the 'driver not found'-error.

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: latest (sha256:142a64ae1c13f26de86fcf62a8656b837765731d1363c37ed8e76657a2cb904a)
- Kubernetes version (use `kubectl version`): v1.32.0 server, v1.28.2 client
- OS (e.g. from /etc/os-release): Mac OS 15.3.2 (24D81)
- Kernel (e.g. `uname -a`): 24.3.0 Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:24 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6030 arm64
- Install tools: Minikube
- Others:

This issue is consistent on a different machine running on an Intel chip, which rules out problems with the arm64 build specifically.
