### ISSUE TITLE
Lost access to cross-tenant blob container via Entra Application workload identity after 2 hours

### ISSUE THREAD

**Issue by JoeyC-Dev** [kubernetes-sigs/blob-csi-driver#1982]
**What happened**:
When the Pod lifetime reaches around 2 hours, access to blob container lost like below: 
![Image](https://github.com/user-attachments/assets/3033b2a1-b2d2-42bf-bd70-7e39228ac383)

Reproducible in the 2nd attempt:  
![Image](https://github.com/user-attachments/assets/6dfd83c7-9e90-4af4-8be6-b9a8b807376f)

If we delete the Pod and re-create it, it can access the blob container again:
![Image](https://github.com/user-attachments/assets/4216f3af-af5f-4a01-b84f-1be56bcd66ce)

**What you expected to happen**:
The connection keeps. 

**How to reproduce it**:
```bash
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: ${namespace}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${svc}
  namespace: ${namespace}
EOF
```
```bash
volUniqId=${sa}#${container}#$(tr -dc a-zA-Z0-9 < /dev/urandom | head -c 4)
```
```bash
cat <<EOF | kubectl apply -f -
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azureblob-fuse
provisioner: blob.csi.azure.com
parameters:
  skuName: Standard_LRS
reclaimPolicy: Delete
mountOptions:
  - '-o allow_other'
  - '--file-cache-timeout-in-seconds=120'
  - '--use-attr-cache=true'
  - '--cancel-list-on-mount-seconds=10'
  - '-o attr_timeout=120'
  - '-o entry_timeout=120'
  - '-o negative_timeout=120'
  - '--log-level=LOG_WARNING'
  - '--cache-size-mb=1000'
allowVolumeExpansion: true
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: pv-blob-wi
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-fuse
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    volumeHandle: ${volUniqId}
    volumeAttributes:
      storageaccount: ${sa}
      containerName: ${container}
      clientID: ${appClientId}
      resourcegroup: ${rG2}
      tenantID: ${tenant2}
      subscriptionid: ${subscription2}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-blob-wi
  namespace: ${namespace}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-blob-wi
  storageClassName: azureblob-fuse
EOF
```
```bash
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: blobfuse-mount-1
  namespace: ${namespace}
spec:
  serviceAccountName: ${svc}
  containers:
  - name: demo
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do cat /mnt/azure/text; sleep 5; done"]
    volumeMounts:
      - mountPath: /mnt/azure
        name: volume
        readOnly: false
  volumes:
   - name: volume
     persistentVolumeClaim:
       claimName: pvc-blob-wi
EOF
```

**Anything else we need to know?**:
I am using App registration instead of managed identity here for one-to-multi tenant scenario. 
Considered that I do can access data initially, the OIDC/FIDC part should be configured correctly.

Blob CSI Driver won't give any useful log:
```
kubectl logs csi-blob-node-gk65f -n kube-system -c blob
```

**Environment**:

- CSI Driver version: blob-csi:v1.25.5
- Kubernetes version (use `kubectl version`): 1.31.7
- OS (e.g. from /etc/os-release): AKSUbuntu-2204containerd-202504.16.0

**Comment by andyzhangx** [comment]
@JoeyC-Dev if you are using sp, why not use `AzureStorageAuthType: spn` directly in pv config?

```console
# azurestoragespnclientid, azurestoragespntenantid field setting in secret is only supported from v1.21.3
kubectl create secret generic azure-secret --from-literal azurestoragespnclientsecret="xxx" azurestoragespnclientid="xxx" azurestoragespntenantid="xxx" --type=Opaque
```

https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/example/pv-blobfuse-auth.yaml
```yaml
 csi:
    driver: blob.csi.azure.com
    # make sure volumeHandle is unique for every storage blob container in the cluster
    volumeHandle: "{resource-group-name}#{account-name}#{container-name}"
    volumeAttributes:
      resourceGroup: EXISTING_RESOURCE_GROUP_NAME
      storageAccount: EXISTING_STORAGE_ACCOUNT_NAME
      containerName: EXISTING_CONTAINER_NAME
      # refer to https://github.com/Azure/azure-storage-fuse#environment-variables
      AzureStorageAuthType: spn
      AzureStorageSPNClientID:
      AzureStorageSPNTenantID:
    nodeStageSecretRef:  # secret should be stored here, not needed for msi auth type
      name: azure-secret
      namespace: default
```
