### ISSUE TITLE
Support on env which not has azure.json under /etc/kubernetes

### ISSUE THREAD

**Issue by Binyang2014** [kubernetes-sigs/blob-csi-driver#266]
When launching blob-csi node daemon, it requires azure.json or other cloud provider config.
It's better to support on-premise env . And the env which not using AKS but raw VMs.

I think for static Provisioning, there is no need for cloud config such as `tenantId` and `subscriptionId`. I'm not sure why this is checked in `nodeserver`.
https://github.com/kubernetes-sigs/blob-csi-driver/blob/58221649504ea2ffebd150ecd4806a5f3e36d27e/pkg/blobfuse/blobfuse.go#L77

**Comment by andyzhangx** [comment]
`azure.json` has basic info, location, e.g. 
https://github.com/kubernetes-sigs/blob-csi-driver/blob/58221649504ea2ffebd150ecd4806a5f3e36d27e/deploy/example/azure.json#L2

So even it's on-premise env, still needs other info and credentials.
BTW, user could store `azure.json` config into configmap, see instruction here: https://github.com/kubernetes-sigs/blob-csi-driver#prerequisite

**Comment by Binyang2014** [comment]
Thanks @andyzhangx, I follow the doc but  csi-blob-node failed to start. It always logs:
```
I1104 03:20:19.952172       1 azure.go:58] could not read cloud config from secret
I1104 03:20:19.952184       1 azure.go:64] use default AZURE_CREDENTIAL_FILE env var: /etc/kubernetes/azure.json
E1104 03:20:19.952195       1 azure.go:69] Failed to load config from file: /etc/kubernetes/azure.json
F1104 03:20:19.952206       1 blob.go:116] failed to get Azure Cloud Provider, error: Failed to load config from file: /etc/kubernetes/azure.json, cloud not get azure cloud provider
```
I put azure.json into a secret `azure-cloud-provider` in kube-system namespace 
```
root@vm:~# kubectl get secret -n kube-system
NAME                              TYPE     DATA   AGE
azure-cloud-provider              Opaque   1      15h
kubernetes-dashboard-key-holder   Opaque   2      425d
```

In azure.json. I only put tenantId subscriptionId and cloud field. Do I miss some steps?

**Comment by Binyang2014** [comment]
BTW,  `csi-blob-node` can starts normally if I mount the secret as a file under /etc/kubernetes

**Comment by andyzhangx** [comment]
is there any issue now?

**Comment by Binyang2014** [comment]
Sure, seems official doc about how to setup blob-csi not work (For the env which not has azure.json). I hope we can give clear doc for this. Then we can introduce this method to our customer.

**Comment by andyzhangx** [comment]
do you think this doc is ok? https://github.com/kubernetes-sigs/blob-csi-driver#prerequisite
or maybe should refine this doc a little?

**Comment by Binyang2014** [comment]
Actually, I could not deploy CSI successfully according this doc. We could discuss this offline :-)

**Comment by Binyang2014** [comment]
A workaround for this is change node daemonset to
```yaml
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-blob-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-blob-node
  template:
    metadata:
      labels:
        app: csi-blob-node
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: csi-blob-node-sa
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
      priorityClassName: system-node-critical
      tolerations:
        - operator: "Exists"
      containers:
        - name: liveness-probe
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
          image: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v1.1.0
          args:
            - --csi-address=/csi/csi.sock
            - --connection-timeout=3s
            - --health-port=29633
            - --v=5
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: node-driver-registrar
          image: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v1.2.0
          args:
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
            - --v=5
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/blob.csi.azure.com-reg.sock /csi/csi.sock"]
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/blob.csi.azure.com/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: blob
          image: mcr.microsoft.com/k8s/csi/blob-csi:v0.10.0
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - "--metrics-address=0.0.0.0:29635"
          ports:
            - containerPort: 29633
              name: healthz
              protocol: TCP
            - containerPort: 29635
              name: metrics
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 30
          env:
            - name: AZURE_CREDENTIAL_FILE
              valueFrom:
                configMapKeyRef:
                  name: azure-cred-file
                  key: path
                  optional: true
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet/
              mountPropagation: Bidirectional
              name: mountpoint-dir
            - mountPath: /etc/kubernetes/azure.json
              name: azure-cred
              subPath: cloud-config
            - mountPath: /var/lib/waagent/ManagedIdentity-Settings
              readOnly: true
              name: msi
            - mountPath: /mnt
              name: blob-cache
          resources:
            limits:
              cpu: 2
              memory: 2100Mi
            requests:
              cpu: 10m
              memory: 20Mi
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/blob.csi.azure.com
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/
            type: DirectoryOrCreate
          name: mountpoint-dir
        - hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
          name: registration-dir
        - name: azure-cred
          secret:
            secretName: azure-cloud-provider
        - hostPath:
            path: /var/lib/waagent/ManagedIdentity-Settings
          name: msi
        - hostPath:
            path: /mnt
          name: blob-cache
```

And set the secret to ` azure-cloud-provider`
```yaml
apiVersion: v1
data:
  cloud-config: ewogICAgImNsb3VkIjoiQXp1cmVQdWJsaWNDbG91ZCIsCiAgICAidGVuYW50SWQiOiAieHh4eCIsCiAgICAic3Vic2NyaXB0aW9uSWQiOiAieHh4eCIKfQo=
kind: Secret
metadata:
  name: azure-cloud-provider
  namespace: kube-system
type: Opaque

```

**Comment by ZeroMagic** [comment]
Following is the minimum info set. Please ensure that all the required fields are included in your configuration.
```
{
    "cloud": "AzurePublicCloud",
    "tenantId": "xxx",
    "subscriptionId": "xxx",
    "aadClientId": "xxx",
    "aadClientSecret": "xxx",
    "resourceGroup": "xxx"
}
```

**Comment by ams0** [comment]
I still can't make this work. I have a statically provisioned blob in a storage account (different RG than AKS). AKS uses MSI but I want to use my own SP to access the blob. I create an `azure.json`:

```console
az ad sp create-for-rbac -n csiblobs --skip-assignment
```

```json
{
  "cloud": "AzurePublicCloud",
  "tenantId": "tenant",
  "subscriptionId": "sub",
  "aadClientId": "client",
  "aadClientSecret": "secret",
  "resourceGroup": "MC_k8s_spark_westeurope"
}
```

Turn the azure.json into a secret called `azure-cloud-provider` in `kube-system`. Deploy CSI blob with:

```console
helm install blob-csi-driver blob-csi-driver/blob-csi-driver --namespace kube-system
```

I see that it gets the secret:

```
~> k logs -n kube-system csi-blob-node-cvhxn -c blob
I0304 23:03:34.046522       1 main.go:82] set up prometheus server on [::]:29635
I0304 23:03:34.046723       1 blob.go:122]
DRIVER INFORMATION:
-------------------
Build Date: "2021-02-25T14:19:01Z"
Compiler: gc
Driver Name: blob.csi.azure.com
Driver Version: v1.1.0
Git Commit: f74ab3febf1f415d7f4b6b6b14513b4dcc3755b9
Go Version: go1.13.10
Platform: linux/amd64

Streaming logs below:
I0304 23:03:34.047937       1 azure.go:58] reading cloud config from secret
I0304 23:03:34.112376       1 azure_auth.go:232] Using AzurePublicCloud environment
I0304 23:03:34.112471       1 azure_auth.go:117] azure: using client_id+client_secret to retrieve access token
```

But both the controller and the Daemonset mount `/etc/kuberntes` from the host, not the secret:

```
~> kg deploy -n kube-system csi-blob-controller -o yaml
...
      volumes:
      - emptyDir: {}
        name: socket-dir
      - hostPath:
          path: /etc/kubernetes/
          type: Directory
```

in fact the content of `/etc/kubernetes/azure.json` inside the pod is identical to the host', but the MI doesn't have roles on the storage account, the PVC I create:

```
~> cat sc1.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-sc
provisioner: blobfuse.csi.azure.com
parameters:
  skuName: Standard_LRS # available values: Standard_LRS, Standard_GRS, Standard_RAGRS
  resourceGroup: storage
  storageAccount: storeme
  containerName: csi
reclaimPolicy: Retain # if set as "Delete" container would be removed after pvc deletion
volumeBindingMode: Immediate
(⎈ |spark:default)arm64 ➜  csiblob
~> cat pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-csi-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: csi-sc
```

Never gets populated by a PV and remains in Pending state. Logs don't say anything, neither on the controllers or on the csi-blob-node. Tried to mount the secret by modifying the daemonset and deployment manifests like @Binyang2014 Binyang2014:

```yaml
  - name: azure-cred
    secret:
      secretName: azure-cloud-provider
      items:
      - key: cloud-config
        path: azure.json
```

but no luck. What am I doing wrong?
