### ISSUE TITLE
support arbitrary volume id in static pv

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/blob-csi-driver#291]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

Currently in static pv, if there is no secret provided, volume id format must be `rg#accoutname#filesharename`, actually it's not necessary, if user provides following parameters, volume id could be arbitrary string:
```
parameters:
  resourceGroup: EXISTING_RESOURCE_GROUP_NAME
  storageAccount: EXISTING_STORAGE_ACCOUNT_NAME
  containerName: EXISTING_CONTAINER_NAME
```

**Describe alternatives you've considered**

**Additional context**
