### ISSUE TITLE
Non root pods aren't able to use blob storage on CentOS

### ISSUE THREAD

**Issue by vojtechspacir** [kubernetes-sigs/blob-csi-driver#317]
**What happened**:
Unable to access blob mount in the pod:
_nonroot@statefulset-blob-0:/$ ls -la /mnt/_
_ls: cannot access '/mnt/blob': Permission denied_
_total 0_
_drwxr-xr-x 1 root root 18 Jan 15 09:06 ._
_drwxr-xr-x 1 root root 28 Jan 15 09:06 .._
_d????????? ? ?    ?     ?            ? blob_

**What you expected to happen**:
Pods without root (securityContext: runAsUser: 0) should be able to use pv/pvc on blob once **mountOptions -o allow_other** is present in blob driver.

**How to reproduce it**:
Follow the guide from here, deploy non root stateful set:
_https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/deploy/example/statefulset-nonroot.yaml_

**Environment**:
- CSI Driver version: v0.11.0
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"89182bdd065fbcaffefec691908a739d161efc03", GitTreeState:"clean", BuildDate:"2020-12-18T12:02:35Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from /etc/os-release): NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

- Kernel (e.g. `uname -a`): Linux 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by andyzhangx** [comment]
My Ubuntu 18.04 actually works, so it should be related to CentOS:
```
# k exec -it statefulset-blob-0 sh
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          29G   16G   14G  55% /
tmpfs            64M     0   64M   0% /dev
tmpfs           3.4G     0  3.4G   0% /sys/fs/cgroup
blobfuse         14G   41M   13G   1% /mnt/blob
/dev/sdb1        29G   16G   14G  55% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs           3.4G   12K  3.4G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs           3.4G     0  3.4G   0% /proc/acpi
tmpfs           3.4G     0  3.4G   0% /proc/scsi
tmpfs           3.4G     0  3.4G   0% /sys/firmware
$ cd /mnt/blob
$ ls -lt
total 4
-rwxrwxrwx 1 root root 754 Jan 15 12:32 outfile
```

**Comment by andyzhangx** [comment]
@NaraVen do you know why `mountOptions -o allow_other` does not work on CentOS, it works in Ubuntu. And our driver image is a debian based image, using blobfuse 1.3.6, thanks.

**Comment by andyzhangx** [comment]
cc @seguler

**Comment by vojtechspacir** [comment]
I can confirm, that Ubuntu doesn't have this issue.

**Comment by rnarayana** [comment]
Do you mean Host OS being CentOS or container? I'm seeing same issue with Ubuntu 18.04 Host VM, and alpine based container.

**Comment by NaraVen** [comment]
PVC volumes mounted by hostpath always have root as the owner. If the pod is started as a non-root user, it will not be able to able to access the Persisted Volume. Isn't that how AKS is designed @andyzhangx ? 
the -o allow_other is for fuse. it won't change the PV access.
This should not work in Ubuntu either. If it is working then most likely the user in the container is root.

**Comment by vojtechspacir** [comment]
> 
> 
> Do you mean Host OS being CentOS or container? I'm seeing same issue with Ubuntu 18.04 Host VM, and alpine based container.

I have CentOS7 based hosts. Since switching the hosts to Ubuntu, the problem disappear. Container hosted were a mix of base images.

**Comment by ErikLundJensen** [comment]
Maybe this should have been put into another issue, however, it is very related to the permission issue.

When mounting blob inline inside the pod spec then permissions on the folder is neither set. Example
drwxr-xr-x 1 root root  /blob

mountOptions in the volumeAttributes in CSIVolume inside pod spec is not read.
Example from Pod Spec:
```
      - name: blob-storage
        csi:
          driver: blob.csi.azure.com
          readOnly: false          
          volumeAttributes:
            containerName: acontainer
            secretName: azure-blob-secret
            mountOptions: "-o allow_other"
```
nor giving an array as the CSIVolume accepts Strings only:
```
      - name: blob-storage-io
        csi:
          driver: blob.csi.azure.com
          readOnly: false          
          volumeAttributes:
            containerName: acontainer
            secretName: azure-blob-secret
            mountOptions:
              - -o allow_other
```

Thereby using inline CSI Volume in pod forces the pod to run as root as far as I can see.
