### ISSUE TITLE
Helm chart label revision cause pod restarts on Helm upgrade

### ISSUE THREAD

**Issue by wasfree** [kubernetes-sigs/blob-csi-driver#361]
**What happened**:
It seems the helm chart to deploy blob-csi-driver has simular issues than https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/121 .Every time we run our CI/CD pipeline it's triggering a redeployment with container restarts. 

It always try to set the revision to `1` (helm diff):
```
  metadata:
    name: blob-csi-provisioner-binding
    namespace: kube-system
    labels:
      heritage: "Helm"
      release: "pau-blob-csi-driver"
-     revision: "18"
+     revision: "1"
      chart: "blob-csi-driver"
      chartVersion: "1.0.0"
  subjects:
```

**What you expected to happen**:
No changes which cause recreation of pods.

**How to reproduce it**:
Deploy blob-csi-driver with helm and redeploy it again.

**How we can solve this issue?**:
According to the issue mentioned above we should remove revision and heritage labels from [helpers template](https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/charts/latest/blob-csi-driver/templates/_helpers.tpl) and follow helm best practices. 

**Environment**:
- CSI Driver version: v1.0.0
- Kubernetes version (use `kubectl version`): v1.18.14
- OS (e.g. from /etc/os-release): ubuntu 18.04
- Helm: 3.5.2
