### ISSUE TITLE
PVC unable to claim blob storage container but able to claim ADLS Gen 2 filesystem

### ISSUE THREAD

**Issue by DewinGoh** [kubernetes-sigs/blob-csi-driver#449]
**What happened**: 
We created two separate Storage accounts - one with HNS enabled and the other without, and created a container in both SAs. We then deployed storageClasses via the helm chart (dynamic way) for both containers. Then, we created PVCs as per the following settings:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testclaim
  namespace: mynamespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: mystorageclass
```
what happened was that the PVC claim worked for the HNS SA's container (filesystem), but the PVC was unable to claim for the normal blob. The error message on the CSI controller was: 
```
Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"XXX", Name:"XXX", UID:"a95aa9b0-71fd-4edb-b749-935c43f4708d", APIVersion:"v1", ResourceVersion:"24765443", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "XXX": rpc error: code = Unknown desc = failed to create container(common) on account(XXX) type() rg(XXX) location() size(1000), error: storage: service returned error: StatusCode=403, ErrorCode=AuthenticationFailed, ErrorMessage=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:a2897ff7-801e-0019-520b-5c4f42000000
```

**What you expected to happen**: PVC should be able to bind to both HNS and non-HNS SA.

**How to reproduce it**: As per above.

**Anything else we need to know?**: We provided the cluster's kubelet Managed Identity with contributor permissions on both SAs, and created the containers before we created the storageclasses. We have tried various permutations of removing and adding back each component but to no avail. 

**Environment**:
- CSI Driver version: v1.1.0
- Kubernetes version (use `kubectl version`): v1.19.7
