### ISSUE TITLE
Files and directories accessability using ADSL gen2 in AKS

### ISSUE THREAD

**Issue by SiarheiBortnik** [kubernetes-sigs/blob-csi-driver#522]
**What happened**:
Files and directories is not accessible time to time

**What you expected to happen**:
Files and directories should be available in POD imediatly after mounting blob container

**How to reproduce it**:
We are using storageclass, PVC and POD with this PVC as mount point:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: download-storage
mountOptions:
- -o allow_other
- --file-cache-timeout-in-seconds=120
- --use-attr-cache=true
- -o attr_timeout=120
- -o entry_timeout=120
- -o negative_timeout=120
- --use-adls=true
parameters:
  containerName: download-storage
  csi.storage.k8s.io/node-stage-secret-name: accesskey
  csi.storage.k8s.io/node-stage-secret-namespace: test
  csi.storage.k8s.io/provisioner-secret-name: accesskey
  csi.storage.k8s.io/provisioner-secret-namespace: test
  resourceGroup: testgroup
  storageAccount: mystorageaccount123rrr
provisioner: blob.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: pvc-download-storage
  namespace: test
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Ti
  storageClassName: download-storage
  volumeMode: Filesystem
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 500Ti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: test
spec:
  replicas: 6
  selector:
    matchLabels:
      app.kubernetes.io/instance: web-app-qa
      app.kubernetes.io/name: test-web-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: web-app-qa
        app.kubernetes.io/name: test-web-app
    spec:
      containers:
      - env:
        - name: _JAVA_OPTIONS
          value: -Xmx3g -Xms1g -Dlog4j.configuration=file:configs/log4j.xml
        envFrom:
        - secretRef:
            name: web-app-config
        - configMapRef:
            name: web-app-env
        image: myregistry.azurecr.io/web-app:1.0.28.20210928.190
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /app/helpers/gracefully-terminate.sh
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health-check/
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: test-web-app
        ports:
        - containerPort: 8888
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health-check/
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/upload-storage
          name: tmp-storage
        - mountPath: /mnt/pvc-download-storage
          name: main-storage
          readOnly: true
        - mountPath: /app/configs
          name: configs
        - mountPath: /app/static
          name: static
        - mountPath: /app/helpers
          name: scripts
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 14400
      volumes:
      - configMap:
          defaultMode: 420
          name: web-app-configs
        name: configs
      - configMap:
          defaultMode: 448
          name: web-app-scripts
        name: scripts
      - configMap:
          defaultMode: 420
          name: web-app-static
        name: static
      - azureFile:
          secretName: fileshare-secret
          shareName: upload-storage
        name: tmp-storage
      - name: main-storage
        persistentVolumeClaim:
          claimName: pvc-download-storage
          readOnly: true
```
And we have an issue in some PODs (of one deployment) time to time. For some POD with problem file initially we have an error with directory rights:
```
kubectl exec -it -n test web-app-5bd7dc44dd-bst95 -- ls /mnt/pvc-download-storage/folder1/500000000208/001/test1.txt -l
ls: cannot access '/mnt/pvc-download-storage/folder1/500000000208/001/test1.txt': No such file or directory
kubectl exec -it -n test web-app-5bd7dc44dd-bst95 -- ls /mnt/pvc-download-storage/folder1/ -l
ls: cannot access '/mnt/pvc-download-storage/folder1/500000000208': No such file or directory
total 4
drwxr-x--- 3 root root 4096 Jul 8 19:13 500000000001
drwxr-x--- 3 root root 4096 Jul 8 19:13 500000000002
.........................
drwxr-xr-x 3 root root 4096 Sep 28 11:00 500000000206
drwxrwxrwx 3 root root 4096 Sep 28 11:01 500000000207
d????????? ? ? ? ? ? 500000000208
```
But when I run command which should check file existence after few minutes - file appears:

```
kubectl exec -it -n test web-app-5bd7dc44dd-bst95 -- ls /mnt/pvc-download-storage/folder1/500000000208/001/test1.txt -l
-rw-r--r-- 1 root root 300000 Sep 28 11:30 /mnt/pvc-download-storage/folder1/500000000208/001/test1.txt
kubectl exec -it -n test web-app-5bd7dc44dd-bst95 -- ls /mnt/pvc-download-storage/folder1/500000000208/001/test1.txt -l
-rw-r--r-- 1 root root 300000 Sep 28 11:30 /mnt/pvc-download-storage/folder1/500000000208/001/test1.txt
```
PODs uptime about few hours
**Anything else we need to know?**:
Our blob contaner should store millions of file and hundreads Tb of data.
**Environment**:
- CSI Driver version: v1.4.0
- Kubernetes version: v1.20.7 (AKS)
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel: Linux fcms-dropzone-qa-fcms-web-app-5bd7dc44dd-bst95 5.4.0-1048-azure #50~18.04.1-Ubuntu SMP Fri May 14 15:30:12 UTC 2021 x86_64 GNU/Linux
