### ISSUE TITLE
High ADLS gen2 utilization

### ISSUE THREAD

**Issue by SiarheiBortnik** [kubernetes-sigs/blob-csi-driver#575]
**What happened**:
High ADLS gen2 utilization which produce high storage cost

**What you expected to happen**:
Blob fuse driver produce huge amount (about 15.000.000 per 24 hour) of operations such as ListFilesystemDir and GetFileProperties.
![Capture](https://user-images.githubusercontent.com/61515826/143253432-60062fe4-d1ce-4a71-aca3-6315ca9b1e15.PNG)
**How to reproduce it**:
We are using storageclass, PVC and POD with this PVC as mount point:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: download-storage
mountOptions:
- -o allow_other
- --file-cache-timeout-in-seconds=0
- --use-attr-cache=false
- -o attr_timeout=20
- -o entry_timeout=20
- -o negative_timeout=120
- --use-adls=true
- --log-level=LOG_DEBUG
parameters:
  containerName: download-storage
  csi.storage.k8s.io/node-stage-secret-name: accesskey
  csi.storage.k8s.io/node-stage-secret-namespace: test
  csi.storage.k8s.io/provisioner-secret-name: accesskey
  csi.storage.k8s.io/provisioner-secret-namespace: test
  resourceGroup: testgroup
  storageAccount: mystorageaccount123rrr
provisioner: blob.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: pvc-download-storage
  namespace: test
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Ti
  storageClassName: download-storage
  volumeMode: Filesystem
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 500Ti
---
```
We tried to update helm chart from 1.6.0 to 1.7.0 version, but it use the same version of driver. Also we disables all our processes which could use blob container but result was the same. ListFilesystemDir and GetFileProperties are produced by azure-storage-fuse/1.4.1 (example log from our Splunk system):
```
2.0;2021-11-
23T09:03:32.0000125Z;ListFilesystemDir;Success;200;16;16;authenticated;mystorageaccount;mystorageaccount;blob;"https://mystorageaccount.dfs.core
storage?
directory=002/0000000008/000000070875/001&amp;maxResults=2&amp;recursive=false&amp;resource=filesystem";"/mystorageaccount/download-
storage";37014311-201f-006d-3d48-e0441d000000;0;172.18.114.166;2018-11-09;416;0;167;261;0;;;;Monday, 01-Jan-01 00:00:00 GMT;;"azure-storage-
fuse/1.4.1";;;;;;;;;;
2.0;2021-11-
23T09:04:28.0000514Z;GetFileProperties;Success;200;9;9;authenticated;mystorageaccount;mystorageaccount;blob;"https://mystorageaccount.dfs.core.w
storage/002/0000000009/000000082143/001";"/mystorageaccount/download-storage/002/2019/0000000009/000000082143/001";37014f80-201f-
006d-5449-e0441d000000;0;172.18.114.166;2018-11-09;358;0;381;0;0;;;;Sunday, 10-Oct-21 17:54:13 GMT;;"Azure-Storage-Fuse/1.4.1";;;;;;;;;;
2.0;2021-11-
23T09:00:05.0000536Z;GetFileProperties;Success;200;9;8;authenticated;mystorageaccount;mystorageaccount;blob;"https://mystorageaccount.dfs.core.w
storage/004/0000000013";"/mystorageaccount/download-storage/001/2018/0000000013";571c12f1-701f-0070-7948-
e02b24000000;0;155.56.68.229;2018-11-09;341;0;381;0;0;;;;Tuesday, 05-Oct-21 13:20:15 GMT;;"Azure-Storage-Fuse/1.3.6";;;;;;;;;;
```

**Anything else we need to know?**:
Our blob contaner store millions of files and 80 Tb of data.
**Environment**:
- CSI Driver version: v1.4.1
- Kubernetes version: v1.21.2 (AKS)
- OS (e.g. from /etc/os-release): Ubuntu
