### ISSUE TITLE
Adding --streaming=true option results in mount fail

### ISSUE THREAD

**Issue by dg4101** [kubernetes-sigs/blob-csi-driver#617]
**What happened**:

Added --streaming=true in moutOption on StorageClass

```
mountOptions:
  - -o ro
  - -o allow_other
  - --file-cache-timeout-in-seconds=0
  - --cancel-list-on-mount-seconds=60  # prevent billing charges on mounting
  - --log-level=LOG_DEBUG  # LOG_WARNING, LOG_INFO, LOG_DEBUG
  - --streaming=true
```

Pod throw error on mount

```
jetty@webapp:/app$ df -h
df: /mnt/pvc-storage: Transport endpoint is not connected
```

**What you expected to happen**:
mount continue to work and files from the mount to be read by stream instead of going to cache

**How to reproduce it**:

Add `- --streaming=true` option on the storage class and mount data lake blob storage

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: 1.8.0

**Comment by andyzhangx** [comment]
could you try blobfuse mount first? https://github.com/Azure/azure-storage-fuse#mount-options

**Comment by dg4101** [comment]
Could you please elaborate what you meant by "try blobfuse mount first" ?
`--streaming=true` option I added to the storage class is from https://github.com/Azure/azure-storage-fuse#mount-options.

**Comment by andyzhangx** [comment]
@dg4101 could you provide more details about your cluster? 
 - k8s version
 - whether it's aks
 - whether you are using blobfuse-proxy, if yes, what's the blobfuse version on the agent node(`blobfuse -v`)

**Comment by andyzhangx** [comment]
could be related to https://github.com/Azure/azure-storage-fuse/issues/675

**Comment by dg4101** [comment]
@andyzhangx 

Here is info requested.

* k8s version
v1.21.2

* whether it's aks
yes

* whether you are using blobfuse-proxy, if yes, what's the blobfuse version on the agent node(blobfuse -v)
blobfuse 1.4.2

**Comment by andyzhangx** [comment]
so if you remove `- --streaming=true`, does it work? I tried `--streaming=true` with nginx pod, it works well, not sure whether it's related to lake blob storage account.

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blob
provisioner: blob.csi.azure.com
parameters:
  skuName: Premium_LRS  # available values: Standard_LRS, Premium_LRS, Standard_GRS, Standard_RAGRS
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=120
  - --use-attr-cache=true
  - --cancel-list-on-mount-seconds=10  # prevent billing charges on mounting
  - -o attr_timeout=120
  - -o entry_timeout=120
  - -o negative_timeout=120
  - --log-level=LOG_WARNING  # LOG_WARNING, LOG_INFO, LOG_DEBUG
  - --cache-size-mb=1000  # Default will be 80% of available memory, eviction will happen beyond that.
  - -o ro
  - --streaming=true
```
