### ISSUE TITLE
Latest version of helm chart is pointing to wrong version file v0.0.0.tgz

### ISSUE THREAD

**Issue by yriveiro** [kubernetes-sigs/blob-csi-driver#746]
**What happened**:

The latest release of the Helm chart is pointing to an incorrect semversion `v0.0.0`

**What you expected to happen**:

The latest semversion available should be `v1.16.0`

**How to reproduce it**:

[v1.16.0](https://github.com/kubernetes-sigs/blob-csi-driver/tree/master/charts/v1.16.0) has two binaries, the incorrect one and the correct one

**Anything else we need to know?**:

**Environment**:
Not applicable is a release cut issue related.

**Comment by andyzhangx** [comment]
release `v1.16.0` actually points to https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/latest/blob-csi-driver-v1.16.0.tgz, and `latest` points to https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/latest/blob-csi-driver-v0.0.0.tgz, that's expected.

I think we need to remove https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/charts/v1.16.0/blob-csi-driver-v0.0.0.tgz which is not used any more.

```
  - apiVersion: v1
    appVersion: v1.16.0
    created: "2022-08-24T09:34:44.840891107Z"
    description: Azure Blob Storage CSI driver
    digest: bd0fb19f21dc27aea698d79a5255bee02adbcfefd73e6bd420eecab28e763688
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/latest/blob-csi-driver-v1.16.0.tgz
    version: v1.16.0
```
