### ISSUE TITLE
Why spec.capacity.storage is mandatory in PersistentVolumes with driver blob.csi.azure.com ?

### ISSUE THREAD

**Issue by zioproto** [kubernetes-sigs/blob-csi-driver#814]
With reference to this documentation page:
https://learn.microsoft.com/en-us/azure/aks/azure-csi-blob-storage-static?tabs=secret#mount-blob-storage-as-a-volume-using-nfs

I have a question about the API spec for the PersistentVolume, like in the docs example:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: azureblob-nfs-premium
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    # make sure volumeid is unique for every identical storage blob container in the cluster
    # character `#` is reserved for internal use and cannot be used in volumehandle
    volumeHandle: unique-volumeid
    volumeAttributes:
      resourceGroup: resourceGroupName
      storageAccount: storageAccountName
      containerName: containerName
      protocol: nfs
```

Why it is mandatory to specify `spec.capacity.storage` ?

In the Kubernetes API documentation the capacity field is optional:
https://pkg.go.dev/k8s.io/api/core/v1#PersistentVolumeSpec

However it seems that in the implementation of the validations the optionality was not respected, because the API server complains about capacity being required if the field is removed from the yaml file:

```
% kubectl apply -f pv-test.yaml
The PersistentVolume "pv-blob" is invalid:
* spec.capacity: Required value
* spec.capacity: Unsupported value: core.ResourceList(nil): supported values: "storage"
```

Because this storage backend is Azure Blobs, the expectation is that it grows as you write and there should be no need to declare a size value.

It is confusing why the default value in the example is `10Gi`. When looking at the mounted volumes in the Pod process namespace the mount point appears with a maximal size of 5 Petabytes. It seems to me the capacity `10Gi` is completely ignored, however is still relevant when creating PersistentVolumeClaim that checks on the size declared for the PersistentVolume.

Questions:

* Is possible in any ways to create a `PersistentVolume` without declaring the capacity ?
* What is a reasonable default value for `spec.capacity.storage` when using the driver `blob.csi.azure.com` ?

thanks
