### ISSUE TITLE
Refresh mounted files on pod when files inside container in azure storage is updated

### ISSUE THREAD

**Issue by abudavis** [kubernetes-sigs/blob-csi-driver#819]
We were able to mount the files inside an Azure blob container in an Azure storage account on a pod on Openshift (non-ARO).

We were wondering if there is someway to auto-refresh/auto-load the mounted files (at path /mnt/blob) on pod when files inside azure storage container is updated?

As of now, we would have to restart the pod in order for files (inside azure storage container) changes to be picked up.

Example used:

```
oc create -f https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/deploy/example/pvc-blob-csi.yaml
oc create -f https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/deploy/example/nginx-pod-blob.yaml
```

CSI Driver version: master
Openshift 4.10.30

**Comment by andyzhangx** [comment]
@vibhansa-msft do you have any insight on this? thanks.

**Comment by olsenme** [comment]
@abudavis  are you able to provide any more insight on your use case?

**Comment by abudavis** [comment]
@olsenme The use case is quite simple - whenever users update files in a azure container blob, we need those files to be automatically mounted and refreshed in the pod on Openshift. In other words any change on azure container blob files must sync to pod running on Openshift. Today we do this by restarting the pods manually every 5 minutes or so which is clumsy and also the restart takes time as the PVC needs to be unmounted from the current pod. Note that the PVC is automatically refreshed somehow when the files are updated in azure container blob, its the pod that needs to refresh it.

**Comment by andyzhangx** [comment]
> @olsenme The use case is quite simple - whenever users update files in a azure container blob, we need those files to be automatically mounted and refreshed in the pod on Openshift. In other words any change on azure container blob files must sync to pod running on Openshift. Today we do this by restarting the pods manually every 5 minutes or so which is clumsy and also the restart takes time as the PVC needs to be unmounted from the current pod. Note that the PVC is automatically refreshed somehow when the files are updated in azure container blob, its the pod that needs to refresh it.

@abudavis try set `--file-cache-timeout-in-seconds=0` in storage class or pv `mountOptions`:

https://github.com/Azure/azure-storage-fuse/tree/blobfuse-1.4.5#if-your-workload-is-read-only

By setting --file-cache-timeout-in-seconds to 0, you may achieve close-to-open cache consistency like in NFS v3. This means once a file is closed, subsequent opens will see the latest changes from the Blob storage service ignoring the local cache.

**Comment by abudavis** [comment]
I haven't yet tried the above suggested setting, but all of a sudden the pod does not come up, I get this error, any ideas? 

`MountVolume.MountDevice failed for volume "pvc-dea28fd9-135f-43ab-b9e6-c0c817e283db" : rpc error: code = Internal desc = Mount failed with error: exit status 255, output: Unable to start blobfuse. Failed to connect to the storage container. There might be something wrong about the storage config, please double check the storage account name, account key/sas token/OAuth access token and container name. errno=404 Unable to start blobfuse due to authentication or connectivity issues. Please check the readme for valid auth setups. no config filedone reading env vars`

```
$ oc get pvc
NAME       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc-blob   Bound    pvc-dea28fd9-135f-43ab-b9e6-c0c817e283db   10Gi       RWX            blob-fuse      9d
```

Pod definition:

```
kind: Pod
apiVersion: v1
metadata:
  name: nginx-blob
spec:
  nodeSelector:
    "kubernetes.io/os": linux
  containers:
    - image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
      name: nginx-blob
      command:
        - "/bin/sh"
        - "-c"
        - while true; do echo $(date) >> /mnt/blob/outfile; sleep 1; done
      volumeMounts:
        - name: blob01
          mountPath: "/mnt/blob"
  volumes:
    - name: blob01
      persistentVolumeClaim:
        claimName: pvc-blob
```
