### ISSUE TITLE
CreateContainerError on Openshift when pods are restarted

### ISSUE THREAD

**Issue by abudavis** [kubernetes-sigs/blob-csi-driver#824]
We are running blob-csi-driver on non-ARO Openshift. Everything was working fine until we restarted the controller and blob-node pods to simulate a cluster restart at which point the pod using the PVC is stuck at the "CreateContainerError" status with the following error:

`Error: failed to resolve symlink "/var/lib/kubelet/pods/eccf47e9-98af-4e13-bdfa-851cb0fd5b7b/volumes/kubernetes.io~csi/pvc-f6d745f8-5ef9-43e9-a598-dcef3ee47f6d/mount": lstat /var/lib/kubelet/pods/eccf47e9-98af-4e13-bdfa-851cb0fd5b7b/volumes/kubernetes.io~csi/pvc-f6d745f8-5ef9-43e9-a598-dcef3ee47f6d/mount: transport endpoint is not connected`

The workaround is to recreate the PVC and redeploy the pod. We think this is a bug? Please have a look at the pod logs attached.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mount
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: blob-fuse
```

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blob-fuse
mountOptions:
- -o allow_other
- --file-cache-timeout-in-seconds=0
- --use-attr-cache=true
- -o attr_timeout=120
- -o entry_timeout=120
- -o negative_timeout=120
parameters:
  containerName: xxxx
  resourceGroup: xxx
  storageAccount: xxx
provisioner: blob.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
```

The actual environment uses a Kubernetes deployment and not a pod:

```
kind: Pod
apiVersion: v1
metadata:
  name: nginx-blob
spec:
  nodeSelector:
    "kubernetes.io/os": linux
  containers:
    - image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
      name: nginx-blob
      volumeMounts:
        - name: blob01
          mountPath: "/mnt/blob"
  volumes:
    - name: blob01
      persistentVolumeClaim:
        claimName: pvc-mount
```

**Environment**:
- CSI Driver version: master
- Openshift version (use `kubectl version`): 4.10.30
