### ISSUE TITLE
Unable to start blobfuse due to authentication or connectivity issues.

### ISSUE THREAD

**Issue by jj-kroger** [kubernetes-sigs/blob-csi-driver#868]
Have a cluster in VMware that I have confirmed has connectivity to Azure storage account's private endpoint. When using the blob-csi-driver to create a PV and PVC that uses kubernetes secret with storage account name and key I am repeatedly getting the errors shown below. Does anyone have any ideas why this may be happening?

E0406 18:38:06.196268 3608220 utils.go:80] GRPC error: rpc error: code = Aborted desc = An operation with the given Volume ID test-storage-account_test-storage-container already exists
Thu, Apr 6 2023 2:38:39 pm | I0406 18:38:39.298670 3608220 nodeserver.go:183] mount output: Unable to start blobfuse. DNS server lookup failed errno=6
Thu, Apr 6 2023 2:38:39 pm | Unable to start blobfuse due to authentication or connectivity issues. Please check the readme for valid auth setups.
Thu, Apr 6 2023 2:38:39 pm | no config filedone reading env vars
Thu, Apr 6 2023 2:38:39 pm | E0406 18:38:39.298706 3608220 nodeserver.go:371] rpc error: code = Internal desc = Mount failed with error: exit status 255, output: Unable to start blobfuse. DNS server lookup failed errno=6
Thu, Apr 6 2023 2:38:39 pm | Unable to start blobfuse due to authentication or connectivity issues. Please check the readme for valid auth setups.
Thu, Apr 6 2023 2:38:39 pm | no config filedone reading env vars
Thu, Apr 6 2023 2:38:39 pm | E0406 18:38:39.298785 3608220 utils.go:80] GRPC error: rpc error: code = Internal desc = Mount failed with error: exit status 255, output: Unable to start blobfuse. DNS server lookup failed errno=6
Thu, Apr 6 2023 2:38:39 pm | Unable to start blobfuse due to authentication or connectivity issues. Please check the readme for valid auth setups.
Thu, Apr 6 2023 2:38:39 pm | no config filedone reading env vars

```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: pv-blob
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    # make sure volumeid is unique for every storage blob container in the cluster
    # the # character is reserved for internal use
    volumeHandle: test-storage-account_test-storage-container
    volumeAttributes:
      resourceGroup: test-rg-eastus2
      storageAccount: test-storage-account
      containerName: test-storage-container
      server: test-storage-account.privatelink.blob.core.windows.net
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
```

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-blob

```
```
kind: Pod
apiVersion: v1
metadata:
  name: nginx-blob
spec:
  nodeSelector:
    "kubernetes.io/os": linux
  containers:
    - image: nginx
      name: nginx-blob
      command:
        - "/bin/sh"
        - "-c"
        - while true; do echo $(date) >> /mnt/blob/outfile; sleep 1; done
      volumeMounts:
        - name: blob01
          mountPath: "/mnt/blob"
  volumes:
    - name: blob01
      persistentVolumeClaim:
        claimName: pvc-blob
```
