### ISSUE TITLE
Secret required when using MSI auth for blob storage account with fuse protocol

### ISSUE THREAD

**Issue by carvido1** [kubernetes-sigs/blob-csi-driver#926]
**What happened**:
We have found that using latest version of AKS available in Azure, in this case 1.26.3, the CSI blob driver has stopped working. We were using the version 1.25.3 and the persistent volume claim against a blob storage account was working properly.

The event we receive to identify this bug is the following one:

```plaintext
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    11m                  default-scheduler  Successfully assigned default/nginx-blobfuse-inline-volume to aks-agentpool-10538894-vmss000000
  Warning  FailedMount  7m15s                kubelet            Unable to attach or mount volumes: unmounted volumes=[blob], unattached volumes=[kube-api-access-h8cps blob]: timed out waiting for the condition
  Warning  FailedMount  78s (x13 over 11m)   kubelet            MountVolume.MountDevice failed for volume "pv-blob" : rpc error: code = Internal desc = could not get secret(azure-storage-account-csblobfusetest-secret): secrets "azure-storage-account-csblobfusetest-secret" not found
  Warning  FailedMount  28s (x4 over 9m32s)  kubelet            Unable to attach or mount volumes: unmounted volumes=[blob], unattached volumes=[blob kube-api-access-h8cps]: timed out waiting for the condition
```

**What you expected to happen**:
We expect that an identity assigned to the nodepool where the pod that does the pvc as volumeMount authenticates against the blob storage account and provisions the storage via the blobfuse protocol.

As we use an MSI identity there is no need or requirement of secret for the authentication here, furthermore our setup uses RBAC and has the SAS/access keys disabled for the storage account.

**How to reproduce it**:
To fully reproduce this using the out of the box azure csi blob driver we can create a cluster that uses the blob csi release > 1.19, for example the latest AKS version 1.26.3.
It is also possible to do a regression test spawning an older AKS version like 1.25.5.

After the cluster creation we can use the following manifest (a storage account will be required as well, each cluster could have a different kubelet identity, so give the proper permission to the storage account too):

```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blob-fuse
provisioner: blob.csi.azure.com
parameters:
  skuName: Premium_LRS  # available values: Standard_LRS, Premium_LRS, Standard_GRS, Standard_RAGRS
  storeAccountKey: "false"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=120
  - --use-attr-cache=true
  - --cancel-list-on-mount-seconds=10  # prevent billing charges on mounting
  - -o attr_timeout=120
  - -o entry_timeout=120
  - -o negative_timeout=120
  - --log-level=LOG_WARNING  # LOG_WARNING, LOG_INFO, LOG_DEBUG
  - --cache-size-mb=1000  # Default will be 80% of available memory, eviction will happen beyond that.
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: pv-blob
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: blob-fuse
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: account-name_container-name
    volumeAttributes:
      resourceGroup: __RG__
      storageAccount: __SA__
      containerName: __CN__
      AzureStorageAuthType: MSI
      AzureStorageIdentityObjectID: __ID__
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-blob
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-blob
  storageClassName: blob-fuse
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-blobfuse-inline-volume
spec:
  nodeSelector:
    "kubernetes.io/os": linux
  containers:
    - image: mcr.microsoft.com/oss/nginx/nginx:1.19.5
      name: nginx-blobfuse
      command:
        - "/bin/bash"
        - "-c"
        - set -euo pipefail; while true; do echo $(date) >> /mnt/blobfuse/outfile; sleep 1; done
      volumeMounts:
        - name: blob
          mountPath: "/mnt/blobfuse"
  volumes:
    - name: blob
      persistentVolumeClaim:
        claimName: pvc-blob
```

AKS 1.26.3 output:

```plaintext
➜  pvblob k get no -o wide                                                                                             
NAME                                STATUS   ROLES   AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-agentpool-10538894-vmss000000   Ready    agent   48m   v1.26.3   10.224.0.4    <none>        Ubuntu 22.04.2 LTS   5.15.0-1036-azure   containerd://1.6.18+azure-1
➜  pvblob k get po -n kube-system -l app=csi-blob-node -o jsonpath='{.items[0].spec.containers[*].image}' | tr " " "\n"
mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.6.0
mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.5.0
mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.21.0%                                                                                                                                                            ➜  pvblob k describe pod nginx-blobfuse-inline-volume | grep -A 5 "Events:"                                            
Events:
  Type     Reason       Age                 From               Message
  ----     ------       ----                ----               -------
  Normal   Scheduled    22m                 default-scheduler  Successfully assigned default/nginx-blobfuse-inline-volume to aks-agentpool-10538894-vmss000000
  Warning  FailedMount  17m                 kubelet            Unable to attach or mount volumes: unmounted volumes=[blob], unattached volumes=[kube-api-access-h8cps blob]: timed out waiting for the condition
  Warning  FailedMount  110s (x8 over 20m)  kubelet            Unable to attach or mount volumes: unmounted volumes=[blob], unattached volumes=[blob kube-api-access-h8cps]: timed out waiting for the condition
```

AKS 1.25.3 output:

```plaintext
➜  pvblob k get no -o wide                                                                                             
NAME                                STATUS   ROLES   AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-agentpool-27137485-vmss000000   Ready    agent   46m   v1.25.5   10.224.0.4    <none>        Ubuntu 22.04.2 LTS   5.15.0-1036-azure   containerd://1.6.18+azure-1
➜  pvblob k get po -n kube-system -l app=csi-blob-node -o jsonpath='{.items[0].spec.containers[*].image}' | tr " " "\n"
mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.6.0
mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.5.0
mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.19.4%                                                                                                                                                            ➜  pvblob k describe pod nginx-blobfuse-inline-volume | grep -A 5 "Events:"                                            
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  16m   default-scheduler  Successfully assigned default/nginx-blobfuse-inline-volume to aks-agentpool-27137485-vmss000000
  Normal  Pulling    15m   kubelet            Pulling image "mcr.microsoft.com/oss/nginx/nginx:1.19.5"
  Normal  Pulled     15m   kubelet            Successfully pulled image "mcr.microsoft.com/oss/nginx/nginx:1.19.5" in 2.710542957s
```

**Anything else we need to know?**:
We have used the same storage account for both pv/pvc blob fuse.

**Environment**:

- CSI Driver version: v1.21.0
- Kubernetes version (use `kubectl version`): 1.26.3
- OS (e.g. from /etc/os-release): not relevant
- Kernel (e.g. `uname -a`): not relevant
- Install tools: not relevant
- Others:
