### ISSUE TITLE
Unable to install the 2.0.4 or higher to our AKS cluster

### ISSUE THREAD

**Issue by sacnayak-work** [kubernetes-sigs/blob-csi-driver#990]
**What happened**:
To get the benefit of "-o direct_io" parameter for our AKS (Azure Kubernetes) cluster, we tried patching our cluster to use blob-csi-driver version 2.0.4 . But when we try to patch using the kubectl patch daemonset with value of 2.0.5, it continues to install 2.0.3. We confirmed this by executing **blobfuse2 version** in the blob container of the csi-blob-node pod of kube-system namespace.

**What you expected to happen**:
We were expecting blobfuse2 version to return the version as 2.0.5. 

**How to reproduce it**:
1. Create an AKS cluster 
2. Execute the command ```kubectl patch daemonset csi-blob-node -n kube-system -p '{"spec":{"template":{"spec":{"initContainers":[{"env":[{"name":"INSTALL_BLOBFUSE2","value":"true"},{"name":"BLOBFUSE2_VERSION","value":"2.0.5"}],"name":"install-blobfuse-proxy"}]}}}}'```
3. Identify the csi-blob-node pods which got started.
4. Execute the command ```kubectl exec -it -n kube-system -c blob <pod-name> -- blobfuse2 version```
5. Check the version number displayed. (we get it as 2.0.3, though the version mentioned in the patch is 2.0.5)

**Anything else we need to know?**:
Kubernetes Server version is 1.25.6. Is there any prerequisite version needed for this to run?

**Environment**:

- CSI Driver version: mcr.microsoft.com/oss/kubernetes-csi/blob-csi:**v1.19.5**
- Kubernetes version (use `kubectl version`): client (v1.26.2), server (v1.25.6)
- OS (e.g. from /etc/os-release): Ubuntu 20.04.6 LTS
- Kernel (e.g. `uname -a`): Linux 5.16.2-051602-generic
- Install tools: 
- Others:

**Comment by andyzhangx** [comment]
@sacnayak-work the command `kubectl exec -it -n kube-system -c blob <pod-name> -- blobfuse2 version` only check the built-in version of blob csi driver, and since on AKS, the blob csi driver would use the blobfuse2 on the host directly, you could ssh to the node and run "blobfuse2 --version" directly to check what's the blobfuse2 version on the host.

**Comment by sacnayak-work** [comment]
Thanks for the quick reply Andy. I will continue searching for mechanisms to ssh into the AKS Node Pool host. 

But  I wanted to clarify on the below. 
Our scenario is that we have created a storage class which utilises the Blob Fuse Driver. And have created a simple nginx pod which utilises a Persistent Volume with that Storage Class. Does this use Blob Fuse Driver on the host or the built in version of blob csi driver of the driver container. 

Our storageclass: 
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-test-v2
mountOptions:
- -o allow_other
- --file-cache-timeout-in-seconds=120
parameters:
  containerName: <redacted>
  protocol: fuse2
  resourceGroup: <redacted>
  storageAccount: <redacted>
  storeAccountKey: "false"
  subscriptionID: <redacted>
provisioner: blob.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
```

And our sample PVC:


```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: testcase-storage
  namespace: <redacted>
spec:
  accessModes:
  - ReadWriteMany
  resources:
    limits:
      storage: 1Gi
    requests:
      storage: 1Gi
  storageClassName: storage-class-test-v2
  volumeMode: Filesystem
